### ISSUE TITLE
Aaaand it's gone

### ISSUE THREAD

**Issue by phdoerfler** [beeminder/beemios#15] opened 2019-10-03 19:06 UTC
Version: Current beta.

The stopwatch now is a… card? OK what happens if I slide it down… oooh it's gone and with it any knowledge of how much time I just had amassed on it. Not a fan 😞 

<img width="375" alt="image" src="https://user-images.githubusercontent.com/163428/66156193-7bfd0700-e621-11e9-884d-13108678fbb6.png">

**Comment by andrewpbrett** [comment] 2019-10-03 19:42
That’s not anything we changed, that’s a new iOS 13 behavior.

**Comment by andrewpbrett** [comment] 2019-10-03 20:10
Also this repository is for posterity only, the current repo is [https://github.com/beeminder/BeeSwift](https://github.com/beeminder/BeeSwift)

The issue is fixed in https://github.com/beeminder/BeeSwift/commit/f9c4f46bd4e3632c3229de36361bc5757ede6756

**Closed as completed by andrewpbrett** 2019-10-03 20:10 UTC
